version: '3.8'

services:
  tuwunel:
    image: jevolk/tuwunel:latest
    container_name: matrix-tuwunel
    ports:
      - "6167:6167"
    volumes:
      - ./continuwuity-data:/var/lib/conduwuit
    environment:
      - CONDUWUIT_CONFIG=""
      - CONDUWUIT_SERVER_NAME=localhost
      - CONDUWUIT_DATABASE_PATH=/var/lib/conduwuit
      - CONDUWUIT_PORT=6167
      - CONDUWUIT_ADDRESS=0.0.0.0
      - CONDUWUIT_ALLOW_REGISTRATION=true
      - CONDUWUIT_REGISTRATION_TOKEN=dev-token-123
      - CONDUWUIT_MAX_REQUEST_SIZE=20000000
      - CONDUWUIT_TRUSTED_SERVERS=["matrix.org"]
      - RUST_LOG=debug