version: '3.8'

services:
  conduit:
    image: matrixconduit/matrix-conduit:latest
    container_name: matrix-conduit
    ports:
      - "6167:6167"
    volumes:
      - ./conduit-data:/var/lib/matrix-conduit
    environment:
      - CONDUIT_CONFIG=""
      - CONDUIT_SERVER_NAME=localhost
      - CONDUIT_DATABASE_BACKEND=rocksdb
      - CONDUIT_DATABASE_PATH=/var/lib/matrix-conduit
      - CONDUIT_PORT=6167
      - CONDUIT_ADDRESS=0.0.0.0
      - CONDUIT_ALLOW_REGISTRATION=true
      - CONDUIT_MAX_REQUEST_SIZE=20000000
      - CONDUIT_TRUSTED_SERVERS=["matrix.org"]
      - RUST_LOG=debug