app = 'matrix-server'
primary_region = 'iad'

[build]
  image = 'jevolk/tuwunel:latest'

[env]
  CONDUWUIT_CONFIG = ''
  CONDUWUIT_SERVER_NAME = 'matrix-server.fly.dev'
  CONDUWUIT_DATABASE_PATH = '/var/lib/conduwuit'
  CONDUWUIT_PORT = 6167
  CONDUWUIT_ADDRESS = '0.0.0.0'
  CONDUWUIT_ALLOW_REGISTRATION = true
  CONDUWUIT_REGISTRATION_TOKEN = 'dev-token-123'
  CONDUWUIT_MAX_REQUEST_SIZE = 20000000
  CONDUWUIT_TRUSTED_SERVERS = '["matrix.org"]'
  RUST_LOG = 'debug'

[http_service]
  internal_port = 6167
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

  [[http_service.checks]]
    grace_period = '10s'
    interval = '30s'
    method = 'GET'
    timeout = '5s'
    path = '/_matrix/client/versions'

[vm]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512

[[mounts]]
  source = 'conduwuit_data'
  destination = '/var/lib/conduwuit'