app = 'matrix-conduit-server'
primary_region = 'iad'

[build]
  image = 'matrixconduit/matrix-conduit:latest'

[env]
  CONDUIT_SERVER_NAME = 'your-matrix-server.fly.dev'
  CONDUIT_DATABASE_PATH = '/var/lib/matrix-conduit/'
  CONDUIT_DATABASE_BACKEND = 'rocksdb'
  CONDUIT_PORT = 6167
  CONDUIT_MAX_REQUEST_SIZE = 20000000
  CONDUIT_ALLOW_REGISTRATION = true
  CONDUIT_ALLOW_FEDERATION = true
  CONDUIT_ALLOW_CHECK_FOR_UPDATES = true
  CONDUIT_TRUSTED_SERVERS = '["matrix.org"]'
  CONDUIT_ADDRESS = '0.0.0.0'
  CONDUIT_CONFIG = ''

[http_service]
  internal_port = 6167
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

  [[http_service.checks]]
    grace_period = '10s'
    interval = '30s'
    method = 'GET'
    timeout = '5s'
    path = '/_matrix/client/versions'

[vm]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512

[[mounts]]
  source = 'conduit_data'
  destination = '/var/lib/matrix-conduit'